import React from 'react';
import { Link } from 'react-router-dom';

export default function Home() {
  return (
    <div className="min-h-screen bg-[#0a0a0a] text-slate-200 p-8 md:p-16 font-sans">
      <div className="max-w-4xl mx-auto space-y-12">
        
        {/* Header */}
        <div className="space-y-4 border-b border-white/10 pb-8">
          <h1 className="text-4xl md:text-5xl font-light tracking-widest text-white">
            BELONGIE LAB
          </h1>
          <p className="text-slate-400 text-lg font-light tracking-wide">
            Interactive STEM Demonstrations and Explorations
          </p>
        </div>

        {/* Demo Gallery Grid */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          
          <Link 
            to="/kinetic-matrix" 
            className="group block p-6 bg-[#111111] rounded-xl border border-white/5 hover:border-sky-500/50 hover:bg-[#1a1a1a] transition-all duration-300"
          >
            <h2 className="text-2xl font-light tracking-wider text-white mb-2 group-hover:text-sky-400 transition-colors">
              Kinetic Matrix
            </h2>
            <p className="text-slate-500 text-sm leading-relaxed">
              A continuous loop topology. Observe the mechanical wave dynamics generated by phase-staggered analog paths.
            </p>
          </Link>

          {/* Future demos will go here! */}
          
        </div>
      </div>
    </div>
  );
}