import React from 'react';
import { Link } from 'react-router-dom';

export default function Home() {
  return (
    <div className="min-h-screen bg-[#0a0a0a] text-slate-200 p-8 md:p-16 font-sans">
      <div className="max-w-4xl mx-auto space-y-12">
        
        {/* Header */}
        <div className="space-y-4 border-b border-white/10 pb-8">
          <h1 className="text-4xl md:text-5xl font-light tracking-widest text-white">
            BELONGIE LAB
          </h1>
          <p className="text-slate-400 text-lg font-light tracking-wide">
            Interactive STEM Demonstrations and Explorations
          </p>
        </div>

        {/* Demo Gallery Grid */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          
          <Link 
            to="/kinetic-matrix" 
            className="group block p-6 bg-[#111111] rounded-xl border border-white/5 hover:border-sky-500/50 hover:bg-[#1a1a1a] transition-all duration-300"
          >
            <h2 className="text-2xl font-light tracking-wider text-white mb-2 group-hover:text-sky-400 transition-colors">
              Kinetic Matrix
            </h2>
            <p className="text-slate-500 text-sm leading-relaxed">
              A continuous loop topology. Observe the mechanical wave dynamics generated by phase-staggered analog paths.
            </p>
          </Link>

          <a 
            href="/logarithms.html" 
            className="group block p-6 bg-[#111111] rounded-xl border border-white/5 hover:border-yellow-500/50 hover:bg-[#1a1a1a] transition-all duration-300"
          >
            <h2 className="text-2xl font-light tracking-wider text-white mb-2 group-hover:text-yellow-400 transition-colors">
              Visualizing Logarithms
            </h2>
            <p className="text-slate-500 text-sm leading-relaxed">
              A scrollytelling journey explaining exponents, Euler's number, and the additive superpower of logarithms.
            </p>
          </a>

          <a
            href="/pulleys.html"
            className="group block p-6 bg-[#111111] rounded-xl border border-white/5 hover:border-orange-500/50 hover:bg-[#1a1a1a] transition-all duration-300"
          >
            <h2 className="text-2xl font-light tracking-wider text-white mb-2 group-hover:text-orange-400 transition-colors">
              Mechanical Advantage
            </h2>
            <p className="text-slate-500 text-sm leading-relaxed">
              An interactive physics simulation demonstrating load distribution and force multipliers through pulley systems.
            </p>
          </a>

          <a 
            href="/towers-of-hanoi.html" 
            className="group block p-6 bg-[#111111] rounded-xl border border-white/5 hover:border-purple-500/50 hover:bg-[#1a1a1a] transition-all duration-300"
          >
            <h2 className="text-2xl font-light tracking-wider text-white mb-2 group-hover:text-purple-400 transition-colors">
              Towers of Hanoi
            </h2>
            <p className="text-slate-500 text-sm leading-relaxed">
              Explore recursion, exponential growth, and binary counting through this classic interactive mathematical puzzle.
            </p>
          </a>

          <a 
            href="/mandelbrot.html" 
            className="group block p-6 bg-[#111111] rounded-xl border border-white/5 hover:border-indigo-500/50 hover:bg-[#1a1a1a] transition-all duration-300"
          >
            <h2 className="text-2xl font-light tracking-wider text-white mb-2 group-hover:text-indigo-400 transition-colors">
              The Mandelbrot Set
            </h2>
            <p className="text-slate-500 text-sm leading-relaxed">
              Embark on a journey into infinite complexity arising from a very simple rule, featuring a fully interactive WebGL explorer mode.
            </p>
          </a>

          <a 
            href="/newton-root.html" 
            className="group block p-6 bg-[#111111] rounded-xl border border-white/5 hover:border-emerald-500/50 hover:bg-[#1a1a1a] transition-all duration-300"
          >
            <h2 className="text-2xl font-light tracking-wider text-white mb-2 group-hover:text-emerald-400 transition-colors">
              Newton's Method
            </h2>
            <p className="text-slate-500 text-sm leading-relaxed">
              Discover how to calculate square roots without a calculator by using calculus and tangent lines to rapidly zero in on the answer.
            </p>
          </a>

          <a 
            href="/monty-hall.html" 
            className="group block p-6 bg-[#111111] rounded-xl border border-white/5 hover:border-amber-500/50 hover:bg-[#1a1a1a] transition-all duration-300"
          >
            <h2 className="text-2xl font-light tracking-wider text-white mb-2 group-hover:text-amber-400 transition-colors">
              The Monty Hall Problem
            </h2>
            <p className="text-slate-500 text-sm leading-relaxed">
              A classic probability puzzle. Unpack the math behind the infamous game show scenario through interactive scrollytelling and a live simulator.
            </p>
          </a>

          <a 
            href="/taylor-series.html" 
            className="group block p-6 bg-[#111111] rounded-xl border border-white/5 hover:border-pink-500/50 hover:bg-[#1a1a1a] transition-all duration-300"
          >
            <h2 className="text-2xl font-light tracking-wider text-white mb-2 group-hover:text-pink-400 transition-colors">
              Visualizing Taylor Series
            </h2>
            <p className="text-slate-500 text-sm leading-relaxed">
              Discover how computers calculate functions like sine and cosine by building polynomial approximations step-by-step using Taylor Series.
            </p>
          </a>

          <a 
            href="/trampolines.html" 
            className="group block p-6 bg-[#111111] rounded-xl border border-white/5 hover:border-cyan-500/50 hover:bg-[#1a1a1a] transition-all duration-300"
          >
            <h2 className="text-2xl font-light tracking-wider text-white mb-2 group-hover:text-cyan-400 transition-colors">
              Physics of Trampolines
            </h2>
            <p className="text-slate-500 text-sm leading-relaxed">
              Explore Hooke's Law and energy conservation through a real-time, interactive 1D physics sandbox featuring live phase space trajectories.
            </p>
          </a>

          <Link 
            to="/percentages" 
            className="group block p-6 bg-[#111111] rounded-xl border border-white/5 hover:border-teal-500/50 hover:bg-[#1a1a1a] transition-all duration-300"
          >
            <h2 className="text-2xl font-light tracking-wider text-white mb-2 group-hover:text-teal-400 transition-colors">
              The Magic of Percentages
            </h2>
            <p className="text-slate-500 text-sm leading-relaxed">
              A scrollytelling journey explaining fractions, percentages, and the "magic mirror trick" for doing complex math in your head.
            </p>
          </Link>

          <Link 
            to="/birthday-paradox" 
            className="group block p-6 bg-[#111111] rounded-xl border border-white/5 hover:border-blue-500/50 hover:bg-[#1a1a1a] transition-all duration-300"
          >
            <h2 className="text-2xl font-light tracking-wider text-white mb-2 group-hover:text-blue-400 transition-colors">
              Probability Quest
            </h2>
            <p className="text-slate-500 text-sm leading-relaxed">
              Explore the Birthday Paradox and the math behind Roblox drop rates in this interactive scrollytelling adventure.
            </p>
          </Link>
          
          {/* Future demos will go here! */}
          
        </div>
      </div>
    </div>
  );
}
